"""empty message

Revision ID: 486af05c6bea
Revises: f78767083ec1
Create Date: 2023-10-22 15:58:46.023859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '486af05c6bea'
down_revision = 'f78767083ec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thesis_rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thesis_id', sa.Integer(), nullable=True),
    sa.Column('criterion', sa.String(length=255), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['thesis_id'], ['thesis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thesis_rating')
    # ### end Alembic commands ###
