"""empty message

Revision ID: ae0a295ce257
Revises: d0c640d5d1d9
Create Date: 2024-01-28 14:09:13.819171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae0a295ce257'
down_revision = 'd0c640d5d1d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thesis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deadline', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thesis', schema=None) as batch_op:
        batch_op.drop_column('deadline')

    # ### end Alembic commands ###
