"""empty message

Revision ID: d0c640d5d1d9
Revises: 1231670af4f9
Create Date: 2024-01-28 14:04:07.848179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0c640d5d1d9'
down_revision = '1231670af4f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thesis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thesis', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
